In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

In [3]:
x = np.array([1, 2, 3, 4])
y = np.array([2, 3, 5, 4])

In [6]:
df = pd.DataFrame({"x":x, "y":y})
df

x  y
0  1  2
1  2  3
2  3  5
3  4  4

In [7]:
X = df[['x']]
y = df['y']
X

x
0  1
1  2
2  3
3  4

In [8]:
y

0    2
1    3
2    5
3    4
Name: y, dtype: int32

In [10]:
model = LinearRegression()
model.fit(X, y)

LinearRegression()

In [12]:
slope_sklearn = model.coef_
slope_sklearn

array([0.8])

In [13]:
intercept_sklearn = model.intercept_
intercept_sklearn

1.4999999999999996

Using Formula 1

In [21]:
sum_x = np.sum(df['x'])
sum_y = np.sum(df['y'])
sum_xy = np.sum(df['x'] * df['y'])
sum_x2 = np.sum(df['x'] ** 2)
N = len(df['x'])
N

4

In [22]:
slope_formula1 = ((N * sum_xy) - (sum_x * sum_y)) / ((N * sum_x2) - (sum_x ** 2))
slope_formula1

0.8

In [26]:
intercept_formula1 = (sum_y - (slope_formula1 * sum_x)) / N
intercept_formula1

1.5

Formula 2

In [30]:
mean_x = np.sum(df['x']) / N
mean_y = np.sum(df['y']) / N
mean_y

3.5

In [32]:
slope_formula2 = np.sum((df['x'] - mean_x)*(df['y'] - mean_y)) / np.sum((df['x'] - mean_x) ** 2)
slope_formula2

0.8

In [33]:
intercept_formula2 = mean_y - (slope_formula2 * mean_x)
intercept_formula2

1.5

Compare the results

In [34]:
(slope_sklearn, intercept_sklearn)

(array([0.8]), 1.4999999999999996)

In [36]:
(slope_formula1, intercept_formula1)

(0.8, 1.5)

In [37]:
(slope_formula2, intercept_formula2)

(0.8, 1.5)

In [38]:
pred = model.predict(df[['x']])
pred

array([2.3, 3.1, 3.9, 4.7])

In [39]:
df['pred'] = pred
df

x  y  pred
0  1  2   2.3
1  2  3   3.1
2  3  5   3.9
3  4  4   4.7

In [40]:
df['residual'] = df['y'] - df['pred']
df

x  y  pred  residual
0  1  2   2.3      -0.3
1  2  3   3.1      -0.1
2  3  5   3.9       1.1
3  4  4   4.7      -0.7

Calculate L1 loss

In [41]:
L1_loss = df['residual'].abs().sum()
L1_loss

2.1999999999999997

Calculate L2 loss

In [42]:
L2_loss = (df['residual'] ** 2).sum()
L2_loss

1.8000000000000003

In [43]:
from sklearn.metrics import mean_squared_error, mean_absolute_error

In [46]:
mse = mean_squared_error(df['y'], df['pred'])
mse

0.45000000000000007

In [47]:
mae = mean_absolute_error(df['y'], df['pred'])
mae

0.5499999999999999

In [48]:
import math
rmse = math.sqrt(mse)
rmse

0.6708203932499369